nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: BileMo
            description: This is an API for project 7 of the PHP/Symfony course on Openclassrooms
            version: 0.1.2
        host: 127.0.0.1:8000
        schemes: [http, https]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/login
            - ^/register
