#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /api/register
    controller: App\Controller\SecurityController::register
    methods: POST
api_login_check:
    path: /api/login_check
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }